### ISSUE TITLE
容器镜像自动化构建

### ISSUE THREAD

**Issue by taoky** [USTC-vlab/discussions#17]
Idea 来源于 LUG 的查询机镜像生成器：<https://github.com/ustclug/liimstrap>

设计目标：能够在 Docker 中完成构建，这样每次修改也不需要解包再打包，还要担心文件权限、把 host 的文件删掉之类的问题。

仓库：<https://github.com/USTC-vlab/labstrap>

**Comment by iBug** [comment]
补充：Ubuntu 22.04 镜像

**Comment by taoky** [comment]
基本完工了，现在上线的 22.04 都是 labstrap 构建的了。
